---
# Required facts:
# - snapshot_name

- name: Pull the data from the server
  hosts: telephone
  user: root
  vars_files:
    - env_vars/base.yml
    - env_vars/prod.yml
  vars:
    dump_dir: /tmp
    dump_file: "{{ dump_dir }}/{{ snapshot_name }}.json"
    media_zip: "{{ dump_dir }}/{{ snapshot_name }}.zip"
  tasks:
    - name: Run django manage dumpdata command
      django_manage:
        command: "dumpdata --output {{ dump_file }}"
        app_path: "{{ project_path }}"
        virtualenv: "{{ virtualenv_path }}"
        settings: "{{ django_settings_file }}"
      environment: "{{ django_environment }}"

    - name: Zip up the media directory
      command: zip -r {{ media_zip }} {{ nginx_media_dir }}

    - name: Fetch the data files
      fetch:
        src: "{{ item }}"
        dest: "{{ snapshot_name }}/{{ item | basename }}"
        flat: true
      with_items:
        - "{{ dump_file }}"
        - "{{ media_zip }}"
