---
# Required facts:
# - snapshot_name

- name: Pull the data from the server
  hosts: telephone
  user: root
  vars_files:
    - env_vars/base.yml
    - env_vars/prod.yml
  vars:
    dump_dir: /tmp/
    dump_file: "{{ dump_dir }}/{{ snapshot_name }}.json"
    media_zip: "{{ dump_dir }}/{{ snapshot_name }}.zip"
  tasks:
    - name: Get info about the dump file
      stat: path={{ dump_file }}
      register: dump_st

    - name: Run django manage dumpdata command
      django_manage:
        command: "dumpdata --output {{ dump_file }}"
        app_path: "{{ project_path }}"
        virtualenv: "{{ virtualenv_path }}"
        settings: "{{ django_settings_file }}"
      environment: "{{ django_environment }}"
      when: force is defined or not dump_st.stat.exists

    - name: Get info about zip file
      stat: path={{ media_zip }}
      register: zip_st

    - name: Zip up the media directory
      command: zip -r {{ media_zip }} {{ nginx_media_dir }}
      when: force is defined or not zip_st.stat.exists

    - name: Fetch the zipped sound files
      fetch:
        src: "{{ media_zip }}"
        dest: "{{ snapshot_name }}/{{ media_zip | basename }}"
        flat: true
      when: force is defined or not zip_st.stat.exists
