---

project_name: telephone-app
application_name: telephone

virtualenv_path: "/webapps/{{ application_name }}"
project_path: "{{ virtualenv_path }}/{{ project_name }}"
application_log_dir: "{{ virtualenv_path }}/logs"
application_log_file: "{{ application_log_dir }}/gunicorn_supervisor.log"

# Node.js related settings, see https://github.com/nodesource/distributions#debinstall for possible values
distro: trusty
node_js_version: node_5.x

git_repo: https://github.com/lupyanlab/telephone.git

# Postgres DB
db_user: "{{ application_name }}"
db_name: "{{ application_name }}"

# Nginx
nginx_http_port: 80
nginx_https_port: 443
nginx_access_log_file: "{{ application_log_dir }}/nginx_access.log"
nginx_error_log_file: "{{ application_log_dir }}/nginx_error.log"
nginx_static_dir: "{{ virtualenv_path }}/static/"
nginx_media_dir: "{{ virtualenv_path }}/media/"

ssl_dest_dir: /etc/ssl

# Gunicorn
gunicorn_user: "{{ application_name }}"
gunicorn_group: webapps
gunicorn_num_workers: 3
gunicorn_max_requests: 0

# Django app settings
run_django_south_migration: yes
run_django_collectstatic: yes

django_environment:
  DJANGO_SETTINGS_MODULE: "{{ django_settings_file }}"
  DJANGO_SECRET_KEY: "{{ django_secret_key }}"
  DATABASE_USER: "{{ db_user }}"
  DATABASE_PASSWORD: "{{ db_password }}"

aws_environment:
  AWS_ACCESS_KEY: "{{ aws_access_key }}"
  AWS_SECRET_KEY: "{{ aws_secret_key }}"
  AWS_REGION: us-west-1
